name: homodynenet
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.5
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - ignite
  - h5py
  - numpy
  - pandas
  - pyarrow
  - scipy
  - tqdm
